type TAGS_TYPES = {
  id: number;
  name: string;
  points: number;
}[];

export const TAGS: TAGS_TYPES = [
  { id: 1, name: "Manchester City", points: 135 },
  { id: 2, name: "Bayern Munich", points: 130 },
  { id: 3, name: "Real Madrid", points: 125 },
  { id: 4, name: "Liverpool", points: 120 },
  { id: 5, name: "Barcelona", points: 115 },
  { id: 6, name: "Paris Saint-Germain", points: 113 },
  { id: 7, name: "Chelsea", points: 110 },
  { id: 8, name: "Manchester United", points: 108 },
  { id: 9, name: "Juventus", points: 107 },
  { id: 10, name: "Atlético Madrid", points: 105 },
  { id: 11, name: "Inter Milan", points: 102 },
  { id: 12, name: "Borussia Dortmund", points: 100 },
  { id: 13, name: "Napoli", points: 98 },
  { id: 14, name: "AC Milan", points: 96 },
  { id: 15, name: "RB Leipzig", points: 94 },
  { id: 16, name: "Sevilla", points: 92 },
  { id: 17, name: "Tottenham Hotspur", points: 90 },
  { id: 18, name: "Arsenal", points: 88 },
  { id: 19, name: "Ajax", points: 86 },
  { id: 20, name: "Porto", points: 84 },
  { id: 21, name: "Benfica", points: 82 },
  { id: 22, name: "Roma", points: 80 },
  { id: 23, name: "Lazio", points: 78 },
  { id: 24, name: "Villarreal", points: 76 },
  { id: 25, name: "Atalanta", points: 74 },
  { id: 26, name: "Bayer Leverkusen", points: 72 },
  { id: 27, name: "Marseille", points: 70 },
  { id: 28, name: "Wolfsburg", points: 68 },
  { id: 29, name: "Zenit Saint Petersburg", points: 66 },
  { id: 30, name: "Borussia Mönchengladbach", points: 64 },
  { id: 31, name: "Lyon", points: 62 },
  { id: 32, name: "Shakhtar Donetsk", points: 60 },
  { id: 33, name: "Sporting CP", points: 58 },
  { id: 34, name: "Leicester City", points: 56 },
  { id: 35, name: "Real Sociedad", points: 54 },
  { id: 36, name: "Monaco", points: 52 },
  { id: 37, name: "PSV Eindhoven", points: 50 },
  { id: 38, name: "Eintracht Frankfurt", points: 48 },
  { id: 39, name: "West Ham United", points: 46 },
  { id: 40, name: "Fiorentina", points: 44 },
  { id: 41, name: "Rangers", points: 42 },
  { id: 42, name: "Celtic", points: 40 },
  { id: 43, name: "Red Bull Salzburg", points: 38 },
  { id: 44, name: "Dynamo Kyiv", points: 36 },
  { id: 45, name: "Olympiacos", points: 34 },
  { id: 46, name: "Fenerbahçe", points: 32 },
  { id: 47, name: "Galatasaray", points: 30 },
  { id: 48, name: "Anderlecht", points: 28 },
  { id: 49, name: "Besiktas", points: 26 },
  { id: 50, name: "Braga", points: 24 }
];
