type TAGS_TYPES = {
  name: string;
  points: number;
}[];

export const TAGS: TAGS_TYPES = [
  { name: "Manchester City", points: 135 },
  { name: "Bayern Munich", points: 130 },
  { name: "Real Madrid", points: 125 },
  { name: "Liverpool", points: 120 },
  { name: "Barcelona", points: 115 },
  { name: "Paris Saint-Germain", points: 113 },
  { name: "Chelsea", points: 110 },
  { name: "Manchester United", points: 108 },
  { name: "Juventus", points: 107 },
  { name: "Atlético Madrid", points: 105 },
  { name: "Inter Milan", points: 102 },
  { name: "Borussia Dortmund", points: 100 },
  { name: "Napoli", points: 98 },
  { name: "AC Milan", points: 96 },
  { name: "RB Leipzig", points: 94 },
  { name: "Sevilla", points: 92 },
  { name: "Tottenham Hotspur", points: 90 },
  { name: "Arsenal", points: 88 },
  { name: "Ajax", points: 86 },
  { name: "Porto", points: 84 },
  { name: "Benfica", points: 82 },
  { name: "Roma", points: 80 },
  { name: "Lazio", points: 78 },
  { name: "Villarreal", points: 76 },
  { name: "Atalanta", points: 74 },
  { name: "Bayer Leverkusen", points: 72 },
  { name: "Marseille", points: 70 },
  { name: "Wolfsburg", points: 68 },
  { name: "Zenit Saint Petersburg", points: 66 },
  { name: "Borussia Mönchengladbach", points: 64 },
  { name: "Lyon", points: 62 },
  { name: "Shakhtar Donetsk", points: 60 },
  { name: "Sporting CP", points: 58 },
  { name: "Leicester City", points: 56 },
  { name: "Real Sociedad", points: 54 },
  { name: "Monaco", points: 52 },
  { name: "PSV Eindhoven", points: 50 },
  { name: "Eintracht Frankfurt", points: 48 },
  { name: "West Ham United", points: 46 },
  { name: "Fiorentina", points: 44 },
  { name: "Rangers", points: 42 },
  { name: "Celtic", points: 40 },
  { name: "Red Bull Salzburg", points: 38 },
  { name: "Dynamo Kyiv", points: 36 },
  { name: "Olympiacos", points: 34 },
  { name: "Fenerbahçe", points: 32 },
  { name: "Galatasaray", points: 30 },
  { name: "Anderlecht", points: 28 },
  { name: "Besiktas", points: 26 },
  { name: "Braga", points: 24 }
];
